fix(kms-core): set NEXTEST_TEST_THREADS to 1

diff --git a/.github/workflows/common-testing.yml b/.github/workflows/common-testing.yml
--- a/.github/workflows/common-testing.yml
+++ b/.github/workflows/common-testing.yml
@@ -312,22 +312,10 @@ jobs:
           RUST_BACKTRACE=full cargo nextest run --profile ci ${ARGS_TESTS:+$ARGS_TESTS}
 
       - name: Publish Test Report
-        if: always()
-        uses: ctrf-io/github-test-reporter@646f98cfc16c6f7a0e1f6100cabe2deb95dd2eef  # v1.0.22
+        uses: mikepenz/action-junit-report@3585e9575db828022551b4231f165eb59a0e74e3  # v5.6.2
+        if: success() || failure() # always run even if the previous step fails
         with:
-          report-path: './target/nextest/ci/junit.xml'
-          integrations-config: |
-            {
-                "junit-to-ctrf": {
-                  "enabled": true,
-                  "action": "convert",
-                  "options": {
-                    "output": "./ctrf-reports/ctrf-report.json",
-                    "toolname": "junit-to-ctrf",
-                    "useSuiteName": false,
-                  }
-                }
-              }
+          report_paths: './target/nextest/ci/junit.xml'
 
       - name: Set Slack color
         id: slack_color
@@ -392,7 +380,7 @@ jobs:
           echo "endpoint_url=${AWS_ENDPOINT}" >> ~/.aws/config &&
           export CARGO_INCREMENTAL=0
           export RUSTFLAGS='-Cinstrument-coverage'
-          cargo llvm-cov nextest run --codecov --output-path codecov.json --profile ci ${ARGS_TESTS:+$ARGS_TESTS}
+          cargo llvm-cov nextest run --codecov --output-path codecov.json ${ARGS_TESTS:+$ARGS_TESTS}
           echo "codecov.json" >> $GITHUB_STEP_SUMMARY
 
       - name: Upload coverage to Codecov
