fix(kms-core): add junit posting in gh

diff --git a/.github/workflows/common-testing.yml b/.github/workflows/common-testing.yml
--- a/.github/workflows/common-testing.yml
+++ b/.github/workflows/common-testing.yml
@@ -285,7 +285,7 @@ jobs:
       # Test execution
       - name: Run Tests
         id: tests
-        # if: ${{ ! inputs.test-coverage || !contains(github.event.pull_request.labels.*.name, 'coverage') }}
+        if: ${{ ! inputs.test-coverage || !contains(github.event.pull_request.labels.*.name, 'coverage') }}
         env:
           # some integration tests run docker compose
           # which builds images which need git access
@@ -380,8 +380,14 @@ jobs:
           echo "endpoint_url=${AWS_ENDPOINT}" >> ~/.aws/config &&
           export CARGO_INCREMENTAL=0
           export RUSTFLAGS='-Cinstrument-coverage'
-          cargo llvm-cov nextest run --codecov --output-path codecov.json ${ARGS_TESTS:+$ARGS_TESTS}
+          cargo llvm-cov nextest run --codecov --output-path codecov.json --profile ci ${ARGS_TESTS:+$ARGS_TESTS}
           echo "codecov.json" >> $GITHUB_STEP_SUMMARY
+
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@3585e9575db828022551b4231f165eb59a0e74e3  # v5.6.2
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: './target/nextest/ci/junit.xml'
 
       - name: Upload coverage to Codecov
         if: ${{ inputs.test-coverage && contains(github.event.pull_request.labels.*.name, 'coverage') }}
