fix(kms-core): run tests with coverage

diff --git a/.github/workflows/common-testing.yml b/.github/workflows/common-testing.yml
--- a/.github/workflows/common-testing.yml
+++ b/.github/workflows/common-testing.yml
@@ -81,6 +81,8 @@ env:
 
 permissions:
   packages: read
+  issues: write
+  pull-requests: write
 
 jobs:
   compile-rust-unit-tests:
@@ -163,6 +165,12 @@ jobs:
           toolchain: ${{ env.RUST_IMAGE_VERSION }}
           components: rustfmt, clippy, llvm-tools-preview
           cache: false
+
+      - name: Install cargo-llvm-cov & nextest
+        if: ${{ inputs.test-coverage && contains(github.event.pull_request.labels.*.name, 'coverage') }}
+        uses: taiki-e/install-action@1dd4d60a583436c5738af3d204f159f44d92f704  # v2.61.0
+        with:
+          tool: cargo-llvm-cov,nextest,grcov
 
       ############################################################################
       # Setup cache for dockerfile and inject in docker
@@ -276,12 +284,6 @@ jobs:
       - name: Linting dylint
         run: cargo dylint --all
 
-      - name: Install cargo-llvm-cov & nextest
-        if: ${{ inputs.test-coverage && contains(github.event.pull_request.labels.*.name, 'coverage') }}
-        uses: taiki-e/install-action@1dd4d60a583436c5738af3d204f159f44d92f704  # v2.61.0
-        with:
-          tool: cargo-llvm-cov,nextest
-
       # Test execution
       - name: Run Tests
         id: tests
@@ -298,6 +300,7 @@ jobs:
           ARGS_TESTS: ${{inputs.args-tests}}
           NEXTEST_RETRIES: 2
           NEXTEST_TEST_THREADS: 1
+          LLVM_PROFILE_FILE: 'cargo-test-%p-%m.profraw'
         run: |
           mkdir -p ~/.aws/ &&
           echo "[default]" > ~/.aws/credentials &&
@@ -310,12 +313,28 @@ jobs:
           echo "endpoint_url=${AWS_ENDPOINT}" >> ~/.aws/config &&
           cat ~/.aws/config &&
           RUST_BACKTRACE=full cargo nextest run --profile ci ${ARGS_TESTS:+$ARGS_TESTS}
+          ls -al ./target/
+          ls -al ./target/debug/
+          ls -al ./target/debug/deps/
+          ls -al ../../target/debug/
+          ls -al ../../target/debug/deps/
+          ~/.cargo/bin/grcov . --binary-path ../../target/debug/deps/ -s . --branch --ignore-not-existing --ignore '../*' --ignore "/*" -o coverage/ -t markdown
+          ~/.cargo/bin/grcov . --binary-path ../../target/debug/deps/ -s . --branch --ignore-not-existing --ignore '../*' --ignore "/*" -o ./ -t lcov
+          cat coverage/markdown.md
+          cat coverage/markdown.md >> "$GITHUB_STEP_SUMMARY"
 
       - name: Publish Test Report
         uses: mikepenz/action-junit-report@3585e9575db828022551b4231f165eb59a0e74e3  # v5.6.2
         if: success() || failure() # always run even if the previous step fails
         with:
           report_paths: './target/nextest/ci/junit.xml'
+
+      - name: Upload coverage to Codecov
+        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7  # v5.5.1
+        with:
+          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
+          files: lcov
+          fail_ci_if_error: true
 
       - name: Set Slack color
         id: slack_color
@@ -356,46 +375,47 @@ jobs:
           if-no-files-found: ignore
 
       # Coverage reporting
-      - name: Generate code coverage
-        if: ${{ inputs.test-coverage && contains(github.event.pull_request.labels.*.name, 'coverage') }}
-        env:
-          # some integration tests run docker compose
-          # which builds images which need private git access
-          # building images in every integration test run is bad
-          AWS_ACCESS_KEY_ID: "minioadmin"
-          AWS_SECRET_ACCESS_KEY: "minioadmin"
-          AWS_DEFAULT_REGION: "eu-north-1"
-          AWS_ENDPOINT: "http://127.0.0.1:9000"
-          BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.GHCR_READ_TOKEN }}
-          ARGS_TESTS: ${{inputs.args-tests}}
-          NEXTEST_TEST_THREADS: 1
-          CARGO_INCREMENTAL: 0
-          RUSTFLAGS: -Cinstrument-coverage
-        run: |
-          mkdir -p ~/.aws/ &&
-          echo "[default]" > ~/.aws/credentials &&
-          echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials &&
-          echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials &&
-          echo "[default]" > ~/.aws/config &&
-          echo "output=json" >> ~/.aws/config &&
-          echo "region=${AWS_DEFAULT_REGION}" >> ~/.aws/config &&
-          echo "endpoint_url=${AWS_ENDPOINT}" >> ~/.aws/config &&
-          cargo llvm-cov nextest run --codecov --output-path codecov.json --profile ci ${ARGS_TESTS:+$ARGS_TESTS}
-          echo "codecov.json" >> $GITHUB_STEP_SUMMARY
+      # - name: Generate code coverage
+      #   if: ${{ inputs.test-coverage && contains(github.event.pull_request.labels.*.name, 'coverage') }}
+      #   env:
+      #     # some integration tests run docker compose
+      #     # which builds images which need private git access
+      #     # building images in every integration test run is bad
+      #     AWS_ACCESS_KEY_ID: "minioadmin"
+      #     AWS_SECRET_ACCESS_KEY: "minioadmin"
+      #     AWS_DEFAULT_REGION: "eu-north-1"
+      #     AWS_ENDPOINT: "http://127.0.0.1:9000"
+      #     BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.GHCR_READ_TOKEN }}
+      #     ARGS_TESTS: ${{inputs.args-tests}}
+      #     NEXTEST_TEST_THREADS: 1
+      #     CARGO_INCREMENTAL: 0
+      #     RUSTFLAGS: -Cinstrument-coverage
+      #     LLVM_PROFILE_FILE: 'cargo-test-%p-%m.profraw'
+      #   run: |
+      #     mkdir -p ~/.aws/ &&
+      #     echo "[default]" > ~/.aws/credentials &&
+      #     echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}" >> ~/.aws/credentials &&
+      #     echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> ~/.aws/credentials &&
+      #     echo "[default]" > ~/.aws/config &&
+      #     echo "output=json" >> ~/.aws/config &&
+      #     echo "region=${AWS_DEFAULT_REGION}" >> ~/.aws/config &&
+      #     echo "endpoint_url=${AWS_ENDPOINT}" >> ~/.aws/config &&
+      #     cargo llvm-cov nextest --codecov --output-path codecov.json --profile ci ${ARGS_TESTS:+$ARGS_TESTS}
+      #     echo "codecov.json" >> "${GITHUB_STEP_SUMMARY}"
 
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@3585e9575db828022551b4231f165eb59a0e74e3  # v5.6.2
-        if: success() || failure() # always run even if the previous step fails
-        with:
-          report_paths: './target/nextest/ci/junit.xml'
+      # - name: Publish Test Report
+      #   uses: mikepenz/action-junit-report@3585e9575db828022551b4231f165eb59a0e74e3  # v5.6.2
+      #   if: success() || failure() # always run even if the previous step fails
+      #   with:
+      #     report_paths: './target/nextest/ci/junit.xml'
 
-      - name: Upload coverage to Codecov
-        if: ${{ inputs.test-coverage && contains(github.event.pull_request.labels.*.name, 'coverage') }}
-        uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7  # v5.5.1
-        with:
-          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
-          files: codecov.json
-          fail_ci_if_error: true
+      # - name: Upload coverage to Codecov
+      #   if: ${{ inputs.test-coverage && contains(github.event.pull_request.labels.*.name, 'coverage') }}
+      #   uses: codecov/codecov-action@5a1091511ad55cbe89839c7260b706298ca349f7  # v5.5.1
+      #   with:
+      #     token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
+      #     files: codecov.json
+      #     fail_ci_if_error: true
 
       # - name: Run Tests with Coverage
       #   if: ${{ inputs.test-coverage && contains(github.event.pull_request.labels.*.name, 'coverage') }}
