fix(ci): test with enclave

diff --git a/.github/workflows/performance-testing.yml b/.github/workflows/performance-testing.yml
--- a/.github/workflows/performance-testing.yml
+++ b/.github/workflows/performance-testing.yml
@@ -30,54 +30,105 @@ on:
         type: boolean
         default: true
       kmsCoreImageTag:
-        description: "KMS Core image tag (if dockerBuild is false)"
+        description: "KMS Core image tag (empty if dockerBuild is true)"
         required: false
         type: string
       kmsCoreClientImageTag:
-        description: "KMS Core client image tag (if dockerBuild is false)"
+        description: "KMS Core client image tag (empty if dockerBuild is true)"
         required: false
         type: string
 
 permissions: {}
 
 jobs:
-  # docker-build:
-  #   if: inputs.dockerBuild == true
-  #   name: docker-build
-  #   permissions:
-  #     actions: read # Required to read workflow run information
-  #     contents: write # Required to checkout repository code
-  #     id-token: write # Required for OIDC authentication
-  #     pull-requests: read # Required to read pull request information
-  #     packages: write # Required to publish Docker images
-  #     attestations: write # Required to create build attestations
-  #   uses: ./.github/workflows/docker-build.yml
-  #   secrets:
-  #     BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
-  #     AWS_ACCESS_KEY_S3_USER: ${{ secrets.AWS_ACCESS_KEY_S3_USER }}
-  #     AWS_SECRET_KEY_S3_USER: ${{ secrets.AWS_SECRET_KEY_S3_USER }}
-  #     SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
-  #     SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
-  #     JOB_SECRET: ${{ secrets.JOB_SECRET }}
-  #     CGR_USERNAME: ${{ secrets.CGR_USERNAME }}
-  #     CGR_PASSWORD: ${{ secrets.CGR_PASSWORD }}
+  docker-build:
+    if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.dockerBuild == true) || github.event_name == 'pull_request'
+    name: docker-build
+    permissions:
+      actions: read # Required to read workflow run information
+      contents: write # Required to checkout repository code
+      id-token: write # Required for OIDC authentication
+      pull-requests: read # Required to read pull request information
+      packages: write # Required to publish Docker images
+      attestations: write # Required to create build attestations
+    uses: ./.github/workflows/docker-build.yml
+    secrets:
+      BLOCKCHAIN_ACTIONS_TOKEN: ${{ secrets.BLOCKCHAIN_ACTIONS_TOKEN }}
+      AWS_ACCESS_KEY_S3_USER: ${{ secrets.AWS_ACCESS_KEY_S3_USER }}
+      AWS_SECRET_KEY_S3_USER: ${{ secrets.AWS_SECRET_KEY_S3_USER }}
+      SLAB_ACTION_TOKEN: ${{ secrets.SLAB_ACTION_TOKEN }}
+      SLAB_BASE_URL: ${{ secrets.SLAB_BASE_URL }}
+      JOB_SECRET: ${{ secrets.JOB_SECRET }}
+      CGR_USERNAME: ${{ secrets.CGR_USERNAME }}
+      CGR_PASSWORD: ${{ secrets.CGR_PASSWORD }}
 
   performance-testing:
     name: performance-testing
-    # needs: docker-build
+    needs: docker-build
+    if: always() && !cancelled()
     runs-on: ubuntu-latest
     env:
       NAMESPACE: "kms-ci"
       DEPLOYMENT_TYPE: ${{ github.event_name == 'workflow_dispatch' && inputs.deploymentType || 'threshold' }}
-      KMS_CHART_VERSION: ${{ github.event_name == 'workflow_dispatch' && inputs.kmsChartVersion || '1.3.1' }}
+      KMS_CHART_VERSION: ${{ github.event_name == 'workflow_dispatch' && inputs.kmsChartVersion || '1.4.1' }}
       TKMS_INFRA_CHART_VERSION: ${{ github.event_name == 'workflow_dispatch' && inputs.tkmsInfraChartVersion || '0.3.0' }}
       SYNC_SECRETS_CHART_VERSION: "0.2.1"
-      # IMAGE_TAG: ${{ needs.docker-build.outputs.image_tag }}
-      IMAGE_TAG: "v0.11.0"
-      PCR0: ${{ needs.docker-build.outputs.enclave_pcr0 }}
-      PCR1: ${{ needs.docker-build.outputs.enclave_pcr1 }}
-      PCR2: ${{ needs.docker-build.outputs.enclave_pcr2 }}
     steps:
+      - name: Check docker build
+        run: |
+          ##########################################################################
+          # CASE DOCKER BUILD FAILED
+          #
+          if ${{ needs.docker-build.result }} == 'failure'
+          then
+            exit 1
+          ##########################################################################
+          # CASE WORKFLOW DISPATH or SCHEDULED WITH DOCKER BUILD
+          #
+          elif ${{ needs.docker-build.result }} == 'success'
+          then
+            echo "DEPLOYMENT_TYPE=${{ github.event_name == 'workflow_dispatch' && inputs.deploymentType || 'thresholdWithEnclave' }}" >> $GITHUB_ENV
+            echo "KMS_CORE_IMAGE_TAG=${{ needs.docker-build.outputs.image_tag }}" >> $GITHUB_ENV
+            echo "KMS_CORE_CLIENT_IMAGE_TAG=${{ needs.docker-build.outputs.image_tag }}" >> $GITHUB_ENV
+            if [[ ${DEPLOYMENT_TYPE} == "thresholdWithEnclave" ]]; then
+              docker pull ghcr.io/zama-ai/kms/core-service-enclave:${{ needs.docker-build.outputs.image_tag }}
+              PCR0=$(docker inspect ghcr.io/zama-ai/kms/core-service-enclave:${{ needs.docker-build.outputs.image_tag }} | jq -r '.[0].Config.Labels["zama.kms.eif_pcr0"]')
+              PCR1=$(docker inspect ghcr.io/zama-ai/kms/core-service-enclave:${{ needs.docker-build.outputs.image_tag }} | jq -r '.[0].Config.Labels["zama.kms.eif_pcr1"]')
+              PCR2=$(docker inspect ghcr.io/zama-ai/kms/core-service-enclave:${{ needs.docker-build.outputs.image_tag }} | jq -r '.[0].Config.Labels["zama.kms.eif_pcr2"]')
+              echo "PCR0=${PCR0}" >> $GITHUB_ENV
+              echo "PCR1=${PCR1}" >> $GITHUB_ENV
+              echo "PCR2=${PCR2}" >> $GITHUB_ENV
+            fi
+            exit 0
+          ##########################################################################
+          # CASE WORKFLOW DISPATH WITHOUT DOCKER BUILD SO WE NEED
+          # - DEPLOYMENT_TYPE
+          # - KMS_CORE_IMAGE_TAG
+          # - KMS_CORE_CLIENT_IMAGE_TAG
+          #
+          elif ${{ needs.docker-build.result }} == 'skipped' \
+              && ${{ github.event_name == 'workflow_dispatch' }} \
+              && ${{ inputs.dockerBuild == false }}
+              && ${{ inputs.kmsCoreImageTag != '' }} \
+              && ${{ inputs.kmsCoreClientImageTag != '' }}
+          then
+            echo "DEPLOYMENT_TYPE=${{ inputs.deploymentType }}" >> $GITHUB_ENV
+            echo "KMS_CORE_IMAGE_TAG=${{ inputs.kmsCoreImageTag }}" >> $GITHUB_ENV
+            echo "KMS_CORE_CLIENT_IMAGE_TAG=${{ inputs.kmsCoreClientImageTag }}" >> $GITHUB_ENV
+            if [[ ${DEPLOYMENT_TYPE} == "thresholdWithEnclave" ]]; then
+              docker pull ghcr.io/zama-ai/kms/core-service-enclave:${{ inputs.kmsCoreImageTag }}
+              PCR0=$(docker inspect ghcr.io/zama-ai/kms/core-service-enclave:${{ inputs.kmsCoreImageTag }} | jq -r '.[0].Config.Labels["zama.kms.eif_pcr0"]')
+              PCR1=$(docker inspect ghcr.io/zama-ai/kms/core-service-enclave:${{ inputs.kmsCoreImageTag }} | jq -r '.[0].Config.Labels["zama.kms.eif_pcr1"]')
+              PCR2=$(docker inspect ghcr.io/zama-ai/kms/core-service-enclave:${{ inputs.kmsCoreImageTag }} | jq -r '.[0].Config.Labels["zama.kms.eif_pcr2"]')
+              echo "PCR0=${PCR0}" >> $GITHUB_ENV
+              echo "PCR1=${PCR1}" >> $GITHUB_ENV
+              echo "PCR2=${PCR2}" >> $GITHUB_ENV
+            fi
+            exit 0
+          else
+            exit 1
+          fi
+
       ################################################################
       # SET UP REQUIRED TOOLS
       #
@@ -119,6 +170,10 @@ jobs:
 
       ################################################################
       # SET UP ENVIRONMENT
+      #
+      - name: Setup environment variable
+        run: |
+
       - name: Checkout Project
         uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
         with:
@@ -191,9 +246,9 @@ jobs:
           # SET PATH SUFFIX
           #
           if [[ "${DEPLOYMENT_TYPE}" == "thresholdWithEnclave" ]]; then
-            PATH_SUFFIX="kms-enclave-ci"
+            echo "PATH_SUFFIX=kms-enclave-ci" >> $GITHUB_ENV
           elif [[ "${DEPLOYMENT_TYPE}" == "threshold" ]]; then
-            PATH_SUFFIX="kms-ci"
+            echo "PATH_SUFFIX=kms-ci" >> $GITHUB_ENV
           fi
 
           ##########################################################################
@@ -206,8 +261,8 @@ jobs:
               --version "${KMS_CHART_VERSION}" \
               --values ./ci/kube-testing/"${DEPLOYMENT_TYPE}"/kms-ci/kms-service/values-"${PATH_SUFFIX}".yaml \
               --values ./ci/kube-testing/"${DEPLOYMENT_TYPE}"/kms-ci/kms-service/values-kms-service-threshold-"${i}"-"${PATH_SUFFIX}".yaml \
-              --set kmsCoreClient.image.tag="${IMAGE_TAG}" \
-              --set kmsCore.image.tag="${IMAGE_TAG}"
+              --set kmsCoreClient.image.tag="${KMS_CORE_CLIENT_IMAGE_TAG}" \
+              --set kmsCore.image.tag="${KMS_CORE_IMAGE_TAG}"
             done
 
           ##########################################################################
@@ -220,8 +275,8 @@ jobs:
               --version "${KMS_CHART_VERSION}" \
               --values ./ci/kube-testing/"${DEPLOYMENT_TYPE}"/kms-ci/kms-service/values-"${PATH_SUFFIX}".yaml \
               --values ./ci/kube-testing/"${DEPLOYMENT_TYPE}"/kms-ci/kms-service/values-kms-service-threshold-"${i}"-"${PATH_SUFFIX}".yaml \
-              --set kmsCoreClient.image.tag="${IMAGE_TAG}" \
-              --set kmsCore.image.tag="${IMAGE_TAG}" \
+              --set kmsCoreClient.image.tag="${KMS_CORE_CLIENT_IMAGE_TAG}" \
+              --set kmsCore.image.tag="${KMS_CORE_IMAGE_TAG}" \
               --set kmsCore.thresholdMode.tls.trustedReleases[0].pcr0="${PCR0}" \
               --set kmsCore.thresholdMode.tls.trustedReleases[0].pcr1="${PCR1}" \
               --set kmsCore.thresholdMode.tls.trustedReleases[0].pcr2="${PCR2}"
@@ -240,8 +295,8 @@ jobs:
           --namespace "${NAMESPACE}" \
           --version "${KMS_CHART_VERSION}" \
           --values ./ci/kube-testing/"${DEPLOYMENT_TYPE}"/kms-ci/kms-service/values-kms-service-init-"${PATH_SUFFIX}".yaml \
-          --set kmsCoreClient.image.tag="${IMAGE_TAG}" \
-          --set kmsCore.image.tag="${IMAGE_TAG}"
+          --set kmsCoreClient.image.tag="${KMS_CORE_CLIENT_IMAGE_TAG}" \
+          --set kmsCore.image.tag="${KMS_CORE_IMAGE_TAG}"
 
           ##########################################################################
           # WAIT FOR DEPLOYMENT OF kms-core-init
@@ -255,8 +310,8 @@ jobs:
           --namespace "${NAMESPACE}" \
           --version "${KMS_CHART_VERSION}" \
           --values ./ci/kube-testing/"${DEPLOYMENT_TYPE}"/kms-ci/kms-service/values-kms-service-gen-keys-"${PATH_SUFFIX}".yaml \
-          --set kmsCoreClient.image.tag="${IMAGE_TAG}" \
-          --set kmsCore.image.tag="${IMAGE_TAG}" \
+          --set kmsCoreClient.image.tag="${KMS_CORE_CLIENT_IMAGE_TAG}" \
+          --set kmsCore.image.tag="${KMS_CORE_IMAGE_TAG}" \
           --wait \
           --wait-for-jobs \
           --timeout=1200s
@@ -268,10 +323,8 @@ jobs:
 
       - name: Run performance testing
         run: |
-          # sed -i "s/<version>/${IMAGE_TAG}/g" ./ci/kube-testing/argo-workflow/test-suite-workflow-"${PATH_SUFFIX}"-req-by-step.yaml
-          # argo submit -n argo ./ci/kube-testing/argo-workflow/test-suite-workflow-"${PATH_SUFFIX}"-req-by-step.yaml
-          sed -i "s/<version>/${IMAGE_TAG}/g" ./ci/kube-testing/argo-workflow/test-suite-workflow-kms-ci-reqbystep-v0.11.0.yaml
-          argo submit -n argo ./ci/kube-testing/argo-workflow/test-suite-workflow-kms-ci-reqbystep-v0.11.0.yaml
+          sed -i "s/<version>/${IMAGE_TAG}/g" ./ci/kube-testing/argo-workflow/test-suite-workflow-"${PATH_SUFFIX}"-req-by-step.yaml
+          argo submit -n argo ./ci/kube-testing/argo-workflow/test-suite-workflow-"${PATH_SUFFIX}"-req-by-step.yaml
           argo logs @latest -f -n "${NAMESPACE}"
 
       - name: Get logs from kms-core
